### ISSUE TITLE
Please include dependency as a sub-module into your project

### ISSUE THREAD

**Issue by nsurgeon** [hatomist/ring_test_task_aes#1]
Compilation failed due to missing dependency 
Scanning dependencies of target ring_test_task_aes
```
[ 50%] Building C object CMakeFiles/ring_test_task_aes.dir/main.c.o
/home/andriy/tmp/ring_test_task_aes/main.c:3:10: fatal error: gcrypt.h: No such file or directory
    3 | #include <gcrypt.h>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/ring_test_task_aes.dir/build.make:63: CMakeFiles/ring_test_task_aes.dir/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/ring_test_task_aes.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by hatomist** [comment]
Can you please specify the Linux distribution and it's version you're trying to run this project on? As far as I know, libgrypt is usually built as a dynamic library and is not meant to be included into a project as a sub-module. Instead, it is added as a dependency in the binary package (or a package build script) and then downloaded via the package manager with the project from the distribution repository. Consequently, I need to know your operation system in order to recommend you the correct package for your system so the project compiles.
For example, I'm using Arch Linux and the right package for me is core/libgcrypt as it has the built library and necessary header files included in it. For the Ubuntu 20.04 it will be libgcrypt20 and libgcrypt20-dev, as header files are usually provided in the "-dev" packages.

**Comment by nsurgeon** [comment]
please include it as a source code 
by requirements should be build from sources

**Comment by hatomist** [comment]
Sure. Created a pull request with an updated build.sh. Works for me on Ubuntu 18.04 with build-essential, cmake, git and wget

**Comment by nsurgeon** [comment]
please merge into master branch
